name: plastic_degrading_enzymes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyter
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - pip:
      - accelerate==0.26.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.8
      - aiosignal==1.3.1
      - attrs==24.2.0
      - bio==1.7.1
      - biopython==1.84
      - biothings-client==0.3.1
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.0.1
      - datetime==5.5
      - dill==0.3.8
      - et-xmlfile==2.0.0
      - evaluate==0.4.3
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gprofiler-official==1.0.0
      - huggingface-hub==0.25.1
      - idna==3.10
      - ilearnplus==1.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lightgbm==4.5.0
      - llvmlite==0.43.0
      - lxml==5.3.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - modlamp==4.3.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mygene==3.2.2
      - mysql-connector-python==8.0.17
      - networkx==3.3
      - nose==1.3.7
      - numba==0.60.0
      - numpy==2.0.2
      - openpyxl==3.1.5
      - pandas==2.2.3
      - patsy==0.5.6
      - pillow==10.4.0
      - pooch==1.8.2
      - protobuf==5.28.2
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - qdarkstyle==3.2.3
      - qtpy==2.4.2
      - regex==2024.9.11
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scikit-posthocs==0.9.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentence-transformers==3.3.0
      - sentencepiece==0.2.0
      - sip==6.9.1
      - statsmodels==0.14.4
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - tokenizers==0.20.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.45.1
      - tslearn==0.6.3
      - tzdata==2024.2
      - umap-learn==0.5.6
      - urllib3==2.2.3
      - xgboost==2.1.2
      - xxhash==3.5.0
      - yarl==1.13.1
      - zope-interface==7.2
